require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Audita' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-location', :path => '../node_modules/react-native-location'
  pod 'react-native-geolocation-service', path: '../node_modules/react-native-geolocation-service'

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  # permissions_path = '../node_modules/react-native-permissions/ios'

  # pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  # pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
  # pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera"
  # pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  # pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-LocationAccuracy', :path => "../node_modules/react-native-permissions/ios/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "../node_modules/react-native-permissions/ios/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "../node_modules/react-native-permissions/ios/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "../node_modules/react-native-permissions/ios/MediaLibrary"
  # pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  # pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
  # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "../node_modules/react-native-permissions/ios/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "../node_modules/react-native-permissions/ios/PhotoLibraryAddOnly"
  # pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
  # pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
  # pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
  # pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"


  target 'AuditaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' }) 

  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Audita-tvOS' do
  # Pods for cmiles-tvOS

  target 'Audita-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end